apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidb-clone
spec:
  capacity:
    storage: 1024Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: blockvolume.csi.oraclecloud.com
    volumeHandle: ocid1.volume.oc1.ap-hyderabad-1.abuhsljr3wuulymxwdjjgje2kfvyqjlsrbo6cm6k472ctc2uhcshxgyeyjca
---
apiVersion: database.oracle.com/v4
kind: SingleInstanceDatabase
metadata:
  name: %SIDB_NAME%
  namespace: %SIDB_NAMESPACE%
spec:

  ## DB edition
  edition: free
  ## Use only alphanumeric characters for sid
  sid: FREE

  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: %SIDB_ADMIN_PWD_SECRET%

  ## Database Image
  image:
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: false

  ## Persistence is optional for prebuilt DB image
  ## if specified, the prebuilt DB datafiles are copied over to the persistant volume before DB startup
  persistence:
   size: 1024Gi
   storageClass: ""
   accessMode: "ReadWriteOnce"
   datafilesVolumeName: "sidb-clone"
   setWritePermissions: true

  ## Count of Database Pods.
  replicas: 1