pipeline {
    agent any
    tools {
        maven "m3"
    }
    environment {
        CLUSTER_NAME=credentials("cbworkshop-cluster-name")
        CLUSTER_NAMESPACE="cloudbank"
        CLUSTER_SERVER_URL=credentials("cbworkshop-cluster-server-url")
        REGION_KEY=credentials("cbworkshop-region-key")
        TENANCY_NAMESPACE=credentials("cbworkshop-tenancy-namespace")
        LAB_UNIQUE_ID=credentials("cbworkshop-unique-id")
        FRONTEND_DOCKER_REGISTRY="${REGION_KEY}.ocir.io/${TENANCY_NAMESPACE}/flowershop/${LAB_UNIQUE_ID}/frontend"
        BACKEND_DOCKER_REGISTRY="${REGION_KEY}.ocir.io/${TENANCY_NAMESPACE}/flowershop/${LAB_UNIQUE_ID}/backend"
    }
    parameters {
        string(name: 'ref_value', defaultValue: '', description: 'Payload ref')
        string(name: 'x_github_event', defaultValue: '', description: 'Header X-Github-Event')
        string(name:  'ref_type', defaultValue: '', description: 'Payload ref_type')
    }
    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'ref_value', value: '$.ref'],
                [key: 'ref_type', value: '$.ref_type']
            ],
            genericHeaderVariables: [
                [key: 'X-Github-Event', regexpFilter: '']

            ],
            causeString: 'Triggered by feature branch creation',
            token: '',
            tokenCredentialId: 'cbworkshop-create-branch-token',

            printContributedVariables: false,
            printPostContent: false,
            silentResponse: false,
            regexpFilterText: '$ref_value',
            regexpFilterExpression: '(^feature/([a-z0-9]+)(/\\w+)*|^release/[0-9]+.[0-9]+|^prerelease/[0-9]+.[0-9]+(.\\w+)*)'
        )
    }
    stages {
        stage('create-feature-branch') {
            when {
                expression { params.ref_value ==~ /^feature\/([a-z0-9]+)(\/\w+)*/ }
                expression { return params.ref_type == "branch" && params.x_github_event == "create" }
                not {equals expected: 1, actual: params.ref_value.split('/').length}
            }
            stages {
                stage("Cleanup & Checkout") {
                    steps {
                        cleanWs()
                        checkout scm
                    }
                }
                stage("provision database") {
                    environment {
                        DATABASENAME="${params.ref_value.split("/")[1].toLowerCase()}"
                        BRANCH="${params.ref_value}"
                        VOLUMEDISPLAYNAME="sidb-clone-${params.ref_value.split("/")[1].toLowerCase()}"
                        SOURCEVOLUMEOCID=credentials("cbworkshop-source-volume-ocid")
                        OCI_CLI_AUTH = "instance_principal"
                    }
                    steps {
                        dir("flowershop/jenkins") {
                            echo 'Cloning Block Volume'
                            sh './create-volume.sh $VOLUMEDISPLAYNAME $SOURCEVOLUMEOCID'

                            script{
                                def props = readProperties file: 'volume.env'
                                env.VOLUME_OCID = props['VOLUME_OCID']
                                echo 'Volume created'
                            }
                            
                            echo 'Generating database for branch $BRANCH'
                            sh "./generate-yaml-file.sh $DATABASENAME ${env.VOLUME_OCID}"
                            sh 'rm -f volume.env'
                        }
                        dir("$WORKSPACE/run") {
                            withKubeCredentials(kubectlCredentials: [[
                            caCertificate: '',
                            clusterName: env.CLUSTER_NAME,
                            contextName: '',
                            credentialsId: "cbworkshop-kubectl-token",
                            namespace: env.CLUSTER_NAMESPACE,
                            serverUrl: env.CLUSTER_SERVER_URL
                            ]]) {
                                script {
                                    echo 'Creating Database $DATABASENAME.'
                                    sh 'kubectl apply -f sidb-create.yaml'
                                }
                                timeout(15) {
                                    waitUntil {
                                        is_database_ready("$DATABASENAME")
                                    }
                                }
                                script {
                                    sh 'kubectl --type=merge -p \'{\"spec\":{\"loadBalancer\": true}}\' patch singleinstancedatabase $DATABASENAME'
                                }
                                timeout(15) {
                                    waitUntil {
                                        is_database_ready("$DATABASENAME")
                                    }
                                }
                            }
                        }
                    }
                }
                stage("notify") {
                    steps {
                        echo "Done! Environment provisioned!"
                    }
                }
            }


        }
        stage('create-release-branch') {
            when {
                expression { params.ref_value ==~ /^release\/\d+\.\d+(\.\w+)*$/ }
                expression { return params.ref_type == "branch" && params.x_github_event == "create" }
            }
            environment {
                RELEASE_VERSION="${params.ref_value.split("/")[1]}"
                FRONTEND_APP_IMAGE="${FRONTEND_DOCKER_REGISTRY}:${RELEASE_VERSION}"
                BACKEND_APP_IMAGE="${BACKEND_DOCKER_REGISTRY}:${RELEASE_VERSION}"
                OCIR_HTTP_REGISTRY="https://${REGION_KEY}.ocir.io"
            }
            stages {
                stage("Cleanup & Checkout") {
                    steps {
                        cleanWs()
                        checkout scm
                    }
                }
                stage("build") {
                    steps {
                        dir("flowershop/backend") {
                            sh "mvn clean package"
                            sh "docker build -t ${BACKEND_APP_IMAGE} ."
                        }
                        withCredentials([string(credentialsId: 'cbworkshop-react-pass', variable: 'REACT_PASSKEY')]){
                            dir("flowershop/frontend") {
                                sh '''
                                sed "s|%NAMESPACE%|cloudbank-prod|g" nginx.conf.template > nginx.conf
                                '''
                                sh "docker build --build-arg APP_PASS=${REACT_PASSKEY} --build-arg APP_USER=flowershopadmin -t ${FRONTEND_APP_IMAGE} ."
                            }
                        }
                    }

                }
                stage("push") {
                    steps{
                        dir("flowershop/frontend") {
                            withDockerRegistry(credentialsId: 'cbworkshop_ocir_credentials_id', url: OCIR_HTTP_REGISTRY) {
                                sh "docker push ${FRONTEND_APP_IMAGE}"
                                sh "docker rmi ${FRONTEND_APP_IMAGE}"
                            }
                        }
                        dir("flowershop/backend") {
                            withDockerRegistry(credentialsId: 'cbworkshop_ocir_credentials_id', url: OCIR_HTTP_REGISTRY) {
                                sh "docker push ${BACKEND_APP_IMAGE}"
                                sh "docker rmi ${BACKEND_APP_IMAGE}"
                            }
                        }
                    }
                }
                stage("apply db schema changes") {
                    steps {
                        withCredentials([file(credentialsId: 'cbworkshop-prod-adb-wallet', variable: 'WALLET')]) {
                        withCredentials([string(credentialsId: 'cbworkshop-default-db-password', variable: 'PASSWORD')]) {
                        withCredentials([string(credentialsId: 'cbworkshop-prod-adb-dbname', variable: 'DBNAME')]) {
                            dir("$WORKSPACE/flowershop/db-schema-changes") {
                                sh("./apply-schema-changes.sh ${WALLET} ${PASSWORD} ${DBNAME}_tp ${RELEASE_VERSION}")
                            }
                        }
                        }
                        }
                    }
                }
                stage("deploy") {
                    steps {
                        withKubeCredentials(kubectlCredentials: [[
                            caCertificate: '',
                            clusterName: env.CLUSTER_NAME,
                            contextName: '',
                            credentialsId: "cbworkshop-kubectl-token",
                            namespace: env.CLUSTER_NAMESPACE,
                            serverUrl: env.CLUSTER_SERVER_URL
                            ]]) {
                                sh("kubectl set image deployment/flowershop-backend flowershop-backend=${BACKEND_APP_IMAGE} -n cloudbank-prod")
                                sh("kubectl set image deployment/flowershop-frontend-deployment flowershop-frontend=${FRONTEND_APP_IMAGE} -n cloudbank-prod")
                        }
                    }
                }
                stage("notify") {
                    steps {
                        echo "Done! Deployed to prod environment successfully!"
                    }
                }    
            }
        }
        stage('create-pre-release-branch') {
            when {
                expression { params.ref_value ==~ /^prerelease\/\d+\.\d+(\.\w+)*$/ }
                expression { return params.ref_type == "branch" && params.x_github_event == "create" }
            }
            environment {
                RELEASE_VERSION="${params.ref_value.split("/")[1]}"
                FRONTEND_APP_IMAGE="${FRONTEND_DOCKER_REGISTRY}:${RELEASE_VERSION}"
                BACKEND_APP_IMAGE="${BACKEND_DOCKER_REGISTRY}:${RELEASE_VERSION}"
                OCIR_HTTP_REGISTRY="https://${REGION_KEY}.ocir.io"
            }
            stages {
                stage("Cleanup & Checkout") {
                    steps {
                        cleanWs()
                        checkout scm
                    }
                }
                stage("build") {
                    steps {
                        dir("flowershop/backend") {
                            sh "mvn clean package"
                            sh "docker build -t ${BACKEND_APP_IMAGE} ."
                        }
                        withCredentials([string(credentialsId: 'cbworkshop-react-pass', variable: 'REACT_PASSKEY')]){
                            dir("flowershop/frontend") {
                                sh '''
                                    sed "s|%NAMESPACE%|cloudbank|g" nginx.conf.template > nginx.conf
                                '''
                                sh "docker build --build-arg APP_PASS=${REACT_PASSKEY} --build-arg APP_USER=flowershopadmin -t ${FRONTEND_APP_IMAGE} ."
                            }
                        }
                    }

                }
                stage("push") {
                    steps{
                        dir("flowershop/frontend") {
                            withDockerRegistry(credentialsId: 'cbworkshop_ocir_credentials_id', url: OCIR_HTTP_REGISTRY) {
                                sh "docker push ${FRONTEND_APP_IMAGE}"
                                sh "docker rmi ${FRONTEND_APP_IMAGE}"
                            }
                        }
                        dir("flowershop/backend") {
                            withDockerRegistry(credentialsId: 'cbworkshop_ocir_credentials_id', url: OCIR_HTTP_REGISTRY) {
                                sh "docker push ${BACKEND_APP_IMAGE}"
                                sh "docker rmi ${BACKEND_APP_IMAGE}"
                            }
                        }
                    }
                }
                stage("apply db schema changes") {
                    steps {
                        withCredentials([file(credentialsId: 'cbworkshop-pre-prod-adb-wallet', variable: 'WALLET')]) {
                        withCredentials([string(credentialsId: 'cbworkshop-default-db-password', variable: 'PASSWORD')]) {
                        withCredentials([string(credentialsId: 'cbworkshop-pre-prod-adb-dbname', variable: 'DBNAME')]) {
                            dir("$WORKSPACE/flowershop/db-schema-changes") {
                                sh("./apply-schema-changes.sh ${WALLET} ${PASSWORD} ${DBNAME}_tp ${RELEASE_VERSION}")
                            }
                        }
                        }
                        }
                    }
                }
                stage("deploy") {
                    steps {
                        withKubeCredentials(kubectlCredentials: [[
                            caCertificate: '',
                            clusterName: env.CLUSTER_NAME,
                            contextName: '',
                            credentialsId: "cbworkshop-kubectl-token",
                            namespace: env.CLUSTER_NAMESPACE,
                            serverUrl: env.CLUSTER_SERVER_URL
                            ]]) {
                                sh("kubectl set image deployment/flowershop-backend flowershop-backend=${BACKEND_APP_IMAGE} -n cloudbank")
                                sh("kubectl set image deployment/flowershop-frontend-deployment flowershop-frontend=${FRONTEND_APP_IMAGE} -n cloudbank")
                        }
                    }
                }
                stage("notify") {
                    steps {
                        echo "Done! Deployed to pre-prod environment successfully!"
                    }
                }
            }
        }
    }
}

def is_database_ready(database) {
    try {
        def r = sh script: "kubectl get singleinstancedatabase $database -o 'jsonpath={.status.status}'", returnStdout: true
        return (r == "Healthy")
    } catch (Exception e) {
        echo "Database is still being provisioned. Retrying..."
        return false
    }
}