spring.datasource.url=jdbc:oracle:thin:@cloudbankprod_tp?TNS_ADMIN=/home/opc/wallet
spring.datasource.username=username
spring.datasource.password=password

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
